language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - sudo apt-get install libjpeg62-dev
  - pip install Django==$DJANGO_VERSION
  - pip install -r dev_requirements.txt
  - python setup.py develop
env:
  - DJANGO_VERSION="1.8.5"
  - DJANGO_VERSION="1.9.2"
  - DJANGO_VERSION="1.10"
script: python setup.py test
